blogwebsite/account/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("login", views.login_request, name="login"),
    path("register", views.register_request, name="register"),
    path("logout", views.logout_request, name="logout"),
]

blogwebsite/blog/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

#http://127.0.0.1:8000/
#http://127.0.0.1:8000/index
#http://127.0.0.1:8000/blogs
#http://127.0.0.1:8000/blogs/(değişken int)

urlpatterns = [
    path("",views.index, name="home"),
    path("index",views.index),
    path("blogs",views.blogs, name="blogs"),
    path("blogs/<int:id>",views.blog_details, name="blog_details"),
    path("blogs/write",views.blog_write,name="blogs_write"),
    path("blogs/edit/<int:id>",views.blog_edit,name="blogs_edit"),
    path('blogs/delete/<int:id>', views.blog_delete, name="blogs_delete"),
    path('blogs/catagory/<int:id>', views.blog_by_category, name="blog_by_category")
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

blogwebsite/blogwebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),

]

blogwebsite/account/models.py
from django.db import models

blogwebsite/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

class Category(models.Model): 
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Blog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField(max_length=300)
    summary = models.CharField(max_length=50)
    image1 = models.ImageField(upload_to='blogs')
    image2 = models.ImageField(upload_to='blogs')
    categories = models.ManyToManyField(Category)


    def __str__(self):
        return self.title

blogwebsite/account/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User



def login_request(request):
    if request.user.is_authenticated:
        return redirect("home")
    
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username = username, password = password)
        if user is not None:
            login(request, user)
            return redirect("home")
        else:
            return render(request,"account/login.html",
                          {"error": "email or password is wrong"})
    return render(request, "account/login.html")

def register_request(request):
    if request.user.is_authenticated:
        return redirect("home")
    
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        password = request.POST["password"]
        repassword = request.POST["repassword"]

        if password == repassword:
            if User.objects.filter(username=username).exists():
                return render(request, "account/register.html",{"error":"Username already exists"})
            elif User.objects.filter(email=email).exists():
                return render(request, "account/register.html",{"error":"Email already exists"})
            else:
                user = User.objects.create_user(username=username,email=email,first_name=firstname,last_name=lastname,password=password)
                user.save()
                return redirect("login")
        else:
            return render(request, "account/register.html",{"error":"Password does't match"})



    return render(request, "account/register.html")

def logout_request(request):
    logout(request)
    return redirect("home")

blogwebsite/blog/views.py
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from blog.models import Blog,Category

#title = models.CharField(max_length=50)
#content = models.TextField(max_length=300)
#summary = models.CharField(max_length=50)
#image1 = models.ImageField(upload_to='blog_images/')
#image2 = models.ImageField(upload_to='blog_images/')
#categories = models.ManyToManyField(Category)


def index(request):
    context = {
        "blogs": Blog.objects.all(),
        "categories": Category.objects.all(),
    }
    return render(request,"blog/index.html",context)

def blogs(request):
    user_blogs = Blog.objects.filter(user=request.user)
    context = {
        "blogs":user_blogs,
        "categories": Category.objects.all(),
    }
    return render(request,"blog/blogs.html",context)


def blog_details(request, id):
    blog = Blog.objects.get(id = id)
    return render(request,"blog/blog-details.html",{"blog":blog})

def blog_write(request):
    context = {
        "categories": Category.objects.all(),
    }
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        summary = request.POST.get('summary')
        image1 = request.FILES.get('image1')
        image2 = request.FILES.get('image2')
        category_ids = request.POST.getlist('categories')  # Checkbox'ların değerlerini al

        if not category_ids:
            return HttpResponseBadRequest("At least one category must be selected.")

        categories = Category.objects.filter(id__in=category_ids)

        # Blog modeli oluştur ve kaydet
        blog = Blog.objects.create(
            title=title,
            content=content,
            summary=summary,
            image1=image1,
            image2=image2,
            user=request.user
        )
        blog.categories.set(categories)
        return redirect("blogs")

    return render(request,"blog/blog-write.html",context)

def blog_edit(request, id):
    blog = get_object_or_404(Blog, id=id)

    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        summary = request.POST.get('summary')
        image1 = request.FILES.get('image1')
        image2 = request.FILES.get('image2')
        category_ids = request.POST.getlist('categories')

        # Kategori nesnelerini al
        categories = Category.objects.filter(id__in=category_ids)

        # Blog nesnesini güncelle
        blog.title = title
        blog.content = content
        blog.summary = summary
        if image1:
            blog.image1 = image1
        if image2:
            blog.image2 = image2

        # Kategorileri güncelle
        blog.categories.set(categories)
        
        # Değişiklikleri kaydet
        blog.save()

        # Kullanıcıyı blog detayları sayfasına yönlendir
        return HttpResponseRedirect(reverse('blog_details', args=[blog.id]))

    # GET isteği geldiğinde, blog düzenleme formunu göster
    context = {
        'blog': blog,
        'categories': Category.objects.all(),
    }
    return render(request, "blog/blog-edit.html", context)


def blog_delete(request, id):
    blog = Blog.objects.get(id=id)
    blog.delete()
    return redirect("home") 

def blog_by_category(request, id):
    category = Category.objects.get(id=id)
    blogs_in_category = Blog.objects.filter(categories=id)
    
    context = {
        "blogs": blogs_in_category,
        "category": category,
        "categories": Category.objects.all(),
    }
    return render(request, "blog/blogs.html", context)

blogwebsite/blog/templates/blog/blog-details.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{ blog.title }}
{% endblock %}

{% block content %}
<div class="container mt-3">
    <div class="row">
        <div class="col-9 mt-3">
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-3">
                        <img src="{{ blog.image2.url }}" class="img-fluid rounded-start" alt="{{ blog.title }}">
                    </div>
                    <div class="col-md-9">
                        <div class="card-body">
                            <h5 class="card-title">{{ blog.title }}</h5>
                            <p class="card-text">{{ blog.content }}</p>
                            <p class="card-text"><small class="text-muted">Posted by {{ blog.user.username }}</small></p>
                            <p class="card-text">Categories:
                                {% for category in blog.categories.all %}
                                    <span class="badge bg-primary">{{ category.name }}</span>
                                {% endfor %}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blogwebsite/blog/templates/blog/blog-edit.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Edit Blog
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_title" class="form-label">Title</label>
                    <input type="text" class="form-control" id="id_title" name="title" value="{{ blog.title }}">
                </div>

                <div class="mb-3">
                    <label for="id_content" class="form-label">Content</label>
                    <textarea class="form-control" id="id_content" name="content" rows="6">{{ blog.content }}</textarea>
                </div>

                <div class="mb-3">
                    <label for="id_summary" class="form-label">Summary</label>
                    <input type="text" class="form-control" id="id_summary" name="summary" value="{{ blog.summary }}">
                </div>

                <div class="mb-3">
                    <label for="id_image1" class="form-label">Image 1</label>
                    <input type="file" class="form-control" id="id_image1" name="image1">
                </div>

                <div class="mb-3">
                    <label for="id_image2" class="form-label">Image 2</label>
                    <input type="file" class="form-control" id="id_image2" name="image2">
                </div>

                <div class="mb-3">
                    <label class="form-label">Categories</label><br>
                    {% for category in categories %}
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="{{ category.id }}" id="category{{ category.id }}" name="categories"
                                   {% if category in blog.categories.all %}checked{% endif %}>
                            <label class="form-check-label" for="category{{ category.id }}">
                                {{ category.name }}
                            </label>
                        </div>
                    {% endfor %}
                </div>
                
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blogwebsite/blog/templates/blog/blog-write.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Create Blog
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_title" class="form-label">Title</label>
                    <input type="text" class="form-control" id="id_title" name="title">
                </div>

                <div class="mb-3">
                    <label for="id_content" class="form-label">Content</label>
                    <textarea class="form-control" id="id_content" name="content" rows="6"></textarea>
                </div>

                <div class="mb-3">
                    <label for="id_summary" class="form-label">Summary</label>
                    <input type="text" class="form-control" id="id_summary" name="summary">
                </div>

                <div class="mb-3">
                    <label for="id_image1" class="form-label">Image 1</label>
                    <input type="file" class="form-control" id="id_image1" name="image1">
                </div>

                <div class="mb-3">
                    <label for="id_image2" class="form-label">Image 2</label>
                    <input type="file" class="form-control" id="id_image2" name="image2">
                </div>

                <div class="mb-3">
                    <label class="form-label">Categories</label><br>
                    {% for category in categories %}
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="{{ category.id }}" id="category{{ category.id }}" name="categories">
                            <label class="form-check-label" for="category{{ category.id }}">
                                {{ category.name }}
                            </label>
                        </div>
                    {% endfor %}
                </div>
                
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blogwebsite/blog/templates/blog/blogs.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Home Page
{% endblock %}

{% block content %}
<div class="container mt-3">
    <div class="row">
        <div class="col-3">
            {% include 'partials/_category.html' %}
        </div>
        <div class="col-9">
            <h1>My Blogs</h1>
            <hr>
            {% for blog in blogs %}
                {% include 'blog/partials/_card.html' %}
            {% endfor %}
            

        </div>
    </div>
</div>

{% endblock %}
{% block js_files %}
    <script src="{% static 'blog/js/script.js' %}"></script>
{% endblock %}

blogwebsite/blog/templates/blog/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Home Page
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <div class="row">
            <div class="col-3">
                {% include 'partials/_category.html' %}
            </div>
            <div class="col-9">
                <h1>All Blogs</h1>
                <hr>
                {% for blog in blogs %}
                    {% include 'blog/partials/_card.html' %}
                {% endfor %}
                

            </div>
        </div>
    </div>
{% endblock %}
{% block js_files %}
    <script src="{% static 'blog/js/script.js' %}"></script>
{% endblock %}

blogwebsite/blog/templates/blog/partials/_card.html
{% load static %}
<div class="card mb-3">
    <div class="row g-0">
      <div class="col-md-3">
        <img src="{{ blog.image1.url }}" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-9">
        <div class="card-body">
          <h5 class="card-title">
            <a href="{% url 'blog_details' blog.id %}">{{blog.title}}</a>
          </h5>
          <p class="card-text">{{blog.summary}}</p>
          {% if blog.user == request.user %}
            <div class="d-flex justify-content-end">
              <a href="{% url 'blogs_edit' blog.id %}" class="btn btn-primary me-2">Edit</a>
              <span class="mx-1"></span>
              <a href="#" onclick="confirmDelete({{ blog.id }})" class="btn btn-danger me-2">Delete</a>
            </div>
          {% endif %}
          
        </div>
      </div>
    </div>
</div>

<script>
  function confirmDelete(blogId) {
    var confirmation = confirm("Are you sure you want to delete this blog?");
    if (confirmation) {
        window.location.href = "/blogs/delete/" + blogId;
    }
}
</script>

blogwebsite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title%} {% endblock %}</title>
</head>
<body>
    {% include 'partials/_navbar.html' %}
    
    {% block content %}{% endblock %}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    {% block js_files %}{% endblock %}
</body>
</html>

blogwebsite/templates/partials/_category.html
<div class="list-group">
  {% for category in categories  %}
  <a class="list-group-item list-group-item-action text-dark" href="{% url 'blog_by_category' category.id %}">
    {{ category.name }}
  </a>
  {% endfor %}
</div>

blogwebsite/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">BlogAPP</a>
        <ul class="navbar-nav me-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blogs' %}">My Blogs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blogs_write' %}">Write</a>
            </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="">Welcome - {{user.get_full_name|title}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">SignIn</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">SignUp</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>